### ISSUE TITLE
Too Many Cards in Hand

### ISSUE THREAD

**Issue by treyhendon** [Lattyware/massivedecks#140] opened 2020-05-22 02:24 UTC
As we were playing tonight with the built in deck, it appeared that after a round with a black card containing multiple blanks, users were issued twice the number of white cards they should have been.  Our hands grew from 10 to 32 cards within a two hour game.

**Comment by Lattyware** [comment] 2020-05-22 04:39
Yup, I can reproduce this. I'll look into the root cause.

**Comment by Lattyware** [comment] 2020-05-23 22:42
I believe this should have been fixed by a recent update. Please re-open this issue or create a new one if you find it isn't fixed.

**Comment by Lattyware** [comment] 2020-05-27 20:59
Reopening this one as it appears to still be happening.

**Comment by treyhendon** [comment] 2020-05-28 13:40
Bummer.  I'm just getting started with TS (history in C#), but is there anything I can do to help?

**Closed** 2020-05-28 13:47 UTC
Labels: bug, server

**Comment by Lattyware** [comment] 2020-05-28 13:49
I believe I've fixed it with that commit—I couldn't reproduce while testing. The issue was, I believe, that we were adding cards at the end of the beginning of revealing and at the beginning of judging.

As before, if you can reproduce it with the latest version, please reopen this issue or open a new one and let me know the bug is still there.

**Comment by treyhendon** [comment] 2020-05-28 13:57
Ah, that makes sense.  I'm happy to help with the testing - we do a weekly game night on Thursday with friends and have been on the platform for several months.  I'll let you know if this creeps up tonight.  Thanks for all the work!

And yeah, I'll look at some of the help requested tagged items and see if there are any I can jump into.

**Comment by treyhendon** [comment] 2020-05-29 02:29
I received one extra card and remained one card ahead for a few rounds. The good news is that it seemed to self-heal after a few rounds.

I think it was after being czar for a double black card that I was dealt an extra white card. It was possibly after using a custom black card from the new deck tool. I.e. It seemed like I was dealt one white card after a double black even though I didn't discard.
